---
configure_dotfiles: false

homebrew_upgrade_all_packages: false

homebrew_installed_packages:
  - asdf
  - awscli
  - bat
  - figlet
  - git
  - gh
  - hashicorp/tap/terraform
  - htop
  - jq
  - lolcat
  - nvm
  - postgresql@14
  - pyenv
  - pulumi
  - tfenv
  - tldr
  - tree
  - wget
  - zsh

homebrew_taps:
  - homebrew/core
  - homebrew/cask
  - homebrew/cask-drivers

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - 1Password
  - cloudflare-warp
  - elgato-stream-deck
  - dbeaver-community
  - discord
  - docker
  - firefox
  - google-chrome
  - github
  - iterm2
  - keepingyouawake
  - krisp
  - obsidian
  - pgadmin4
  - rectangle
  - slack
  - sublime-text
  - utm
  - yubico-yubikey-manager
  - vagrant
  - via
  - visual-studio-code
  - warp
  - zoom
  - hpedrorodrigues/tools/dockutil # workaround until proper version of dockutil is added to homebrew


configure_dock: true
dockitems_remove: []
dockitems_persist:
  - name: "Google Chrome"
    path: "/Applications/Google Chrome.app/"
    pos: 3
  - name: "Firefox"
    path: "/Applications/Firefox.app/"
    pos: 4
  - name: "Slack"
    path: "/Applications/Slack.app/"
    pos: 5
  - name: "iTerm"
    path: "/Applications/iTerm.app/"
    pos: 6
  - name: "Visual Studio Code"
    path: "/Applications/Visual Studio Code.app/"
    pos: 7
  - name: "Sublime Text"
    path: "/Applications/Sublime Text.app/"
    pos: 8
  - name: "1Password"
    path: "/Applications/1Password.app/"
    pos: 9
